import {createClient} from 'https://esm.sh/@supabase/supabase-js@2';
const sb=createClient('https://ovybstpiomphrouvqxmf.supabase.co','sb_publishable_gU5Wgy2NhdXcy23_TotF9g_LKthVmKV');
const $=id=>document.getElementById(id),admin=document.body.classList.contains('admin');
let slots=[],revision,selected=null,zoom=1,busy=false,lang=localStorage.getItem('hola-language')||'es';
const norm=s=>(s||'').normalize('NFKD').replace(/\p{M}/gu,'').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const en=()=>lang!=='es',say=(es,english)=>en()?english:es;
const canvas=$('map'),ctx=canvas.getContext('2d'),W=3200,H=2400,S=48,L=140,T=150;
canvas.width=W*2;canvas.height=H*2;ctx.scale(2,2);
const px=x=>L+(x-193)*S,py=y=>T+(1000-y)*S;
const images={};
function status(s){$('status').textContent=s}
function label(s){return `${String(s.id).padStart(3,'0')} · ${s.name||say('Libre','Available')} · X${s.x} Y${s.y}`}
function translate(){document.documentElement.lang=en()?'en':'es';$('title').textContent=admin?say('Organización del mapa','Map administration'):say('Mapa de la alianza','Alliance map');$('intro').textContent=say('Encuentra tu nombre y consulta las coordenadas del centro de tu base.','Find your name and the coordinates of your base centre.');$('search-label').textContent=say('Nombre del jugador','Player name');$('search').placeholder=say('Escribe tu nombre','Type your name');for(const [id,a,b] of [['find','Buscar','Search'],['copy','Copiar coordenadas','Copy coordinates'],['download','Descargar mapa HD','Download HD map'],['fit','Ver todo','Fit map']])$(id).textContent=say(a,b);$('language').textContent=en()?'Español':'English';$('map-hint').textContent=say('Desliza para recorrer el mapa. Bases de 3 × 3 casillas. Coordenadas del centro. Límite Y999.','Scroll to explore. Bases occupy 3 × 3 cells. Centre coordinates. Upper limit Y999.');$('terrain-note').textContent=say('Contorno aproximado: comprueba la colocación en el juego.','Approximate terrain outline: verify placement in game.');if(selected)show(selected,false);draw();}
function fit(){zoom=Math.min($('viewport').clientWidth/W,$('viewport').clientHeight/H,1);size();$('viewport').scrollTo({left:0,top:0})}
function size(){canvas.style.width=W*zoom+'px';canvas.style.height=H*zoom+'px'}
function box(x1,y1,x2,y2,fill,stroke){ctx.fillStyle=fill;ctx.fillRect(px(x1),py(y2),(x2-x1)*S,(y2-y1)*S);ctx.strokeStyle=stroke;ctx.lineWidth=3;ctx.strokeRect(px(x1),py(y2),(x2-x1)*S,(y2-y1)*S)}
function text(s,x,y,size=18,color='#163f58'){ctx.fillStyle=color;ctx.font=`600 ${size}px system-ui`;ctx.textAlign='center';ctx.fillText(s,x,y)}
function building(name,x1,y1,x2,y2,title){box(x1,y1,x2,y2,'#c7a366','#9b743f');const im=images[name];if(im){const w=(x2-x1)*S,h=(y2-y1)*S,ratio=Math.min(w/im.width,(h-48)/im.height);ctx.drawImage(im,px(x1)+(w-im.width*ratio)/2,py(y2)+10,im.width*ratio,im.height*ratio)}text(title,(px(x1)+px(x2))/2,py(y1)-15,22)}
function draw(){ctx.fillStyle='#d4b477';ctx.fillRect(0,0,W,H);text('HOLa · '+say('MAPA DE LA ALIANZA','ALLIANCE MAP'),W/2,55,38);text(say('Nombre · coordenadas del centro · bases 3 × 3','Name · centre coordinates · 3 × 3 bases'),W/2,95,21);ctx.strokeStyle='#a58c61';ctx.lineWidth=1;for(let x=193;x<=256;x++){ctx.beginPath();ctx.moveTo(px(x-.5),py(999.5));ctx.lineTo(px(x-.5),py(956.5));ctx.stroke();if((x-195)%5===0)text(x,px(x),132,18)}for(let y=957;y<=1000;y++){ctx.beginPath();ctx.moveTo(px(192.5),py(y-.5));ctx.lineTo(px(256),py(y-.5));ctx.stroke();if(y%5===0)text(y,75,py(y)+6,18)}ctx.strokeStyle='#655132';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(px(192.5),py(999.5));ctx.lineTo(px(256),py(999.5));ctx.stroke();building('center',220.5,986.5,229.5,995.5,say('CENTRO DE ALIANZA','ALLIANCE CENTRE'));building('mountain',218.5,971.5,234.5,986.5,say('MONTAÑA','MOUNTAIN'));building('building',193.5,957.5,196.5,960.5,'X195 · Y959');for(const s of slots){const active=s.id===selected?.id;box(s.x-1.5,s.y-1.5,s.x+1.5,s.y+1.5,active?'#ffe17e':'#c4ecf5',active?'#ba6f00':'#439ab5');text(String(s.id).padStart(3,'0'),px(s.x)-48,py(s.y)-48,16);let name=s.name||say('Libre','Available');ctx.font='600 19px system-ui';const words=[];while(name.length){let n=name.length;while(n>1&&ctx.measureText(name.slice(0,n)).width>132)n--;words.push(name.slice(0,n));name=name.slice(n)}for(let i=0;i<Math.min(words.length,3);i++)text(words[i],px(s.x),py(s.y)-20+i*23,19);text(`X${s.x} Y${s.y}`,px(s.x),py(s.y)+55,17)}text(say('Contorno aproximado · comprueba las posiciones en el juego','Approximate terrain · verify positions in game'),W/2,H-90,22);}
function show(s,focus=true){selected=s;$('selected').textContent=label(s);if(admin){$('slot').value=s.id;$('player').value=s.name||''}draw();if(focus){zoom=Math.max(zoom,.65);size();$('viewport').scrollTo({left:px(s.x)*zoom-$('viewport').clientWidth/2,top:py(s.y)*zoom-$('viewport').clientHeight/2,behavior:'smooth'})}}
function search(){const q=norm($('search').value);$('matches').replaceChildren();if(!q)return;const found=slots.filter(s=>s.name&&norm(s.name).includes(q));for(const s of found){const b=document.createElement('button');b.textContent=label(s);b.onclick=()=>show(s);$('matches').append(b)}if(!found.length)status(say('No hay coincidencias. Comprueba el nombre.','No matches. Check the name.'));else{status('');const exact=found.find(s=>norm(s.name)===q);if(exact||found.length===1)show(exact||found[0])}}
async function refresh(){const {data,error}=await sb.from('alliance_map_config').select('slots,revision').eq('id',1).single();if(error)throw error;slots=data.slots;revision=data.revision;if(admin){$('slot').replaceChildren(...slots.map(s=>{const o=document.createElement('option');o.value=s.id;o.textContent=label(s);return o}));}draw();}
async function save(remove=false){if(busy)return;const target=slots.find(s=>s.id===Number($('slot').value)),name=$('player').value.trim();if(!remove&&!name){status('Escribe un nombre.');return}if(!confirm(remove?`¿Retirar a ${target.name||'este jugador'} del puesto ${target.id}?`:`¿Guardar ${name} en X${target.x} Y${target.y}? Si ya tiene puesto, se intercambiarán los jugadores.`))return;busy=true;$('assign').disabled=$('remove').disabled=true;const next=structuredClone(slots),dest=next.find(s=>s.id===target.id),source=next.find(s=>s.id!==target.id&&norm(s.name)===norm(name));if(source&&!remove)source.name=dest.name;dest.name=remove?null:name;try{const {data,error}=await sb.from('alliance_map_config').update({slots:next}).eq('id',1).eq('revision',revision).select('slots,revision').maybeSingle();if(error)throw error;if(!data){await refresh();throw Error('Otro administrador ha actualizado el mapa. Revisa el cambio y vuelve a guardar.')}slots=data.slots;revision=data.revision;await refresh();show(slots.find(s=>s.id===target.id),false);status('Guardado. El mapa público y las descargas ya incluyen el cambio.')}catch(e){status(e.message||'No se pudo guardar.')}finally{busy=false;$('assign').disabled=$('remove').disabled=false}}
$('language').onclick=()=>{lang=en()?'es':'en';translate()};$('search').oninput=search;$('find').onclick=search;$('search').onkeydown=e=>{if(e.key==='Enter')search()};$('fit').onclick=fit;$('zoom-in').onclick=()=>{zoom=Math.min(2,zoom*1.3);size()};$('zoom-out').onclick=()=>{zoom=Math.max(.15,zoom/1.3);size()};canvas.onclick=e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*W,y=(e.clientY-r.top)/r.height*H;const s=slots.find(s=>Math.abs(x-px(s.x))<1.5*S&&Math.abs(y-py(s.y))<1.5*S);if(s)show(s,false)};
$('copy').onclick=async()=>{if(!selected)return status(say('Selecciona primero un puesto.','Select a position first.'));try{await navigator.clipboard.writeText(`${selected.name||''}: X${selected.x} Y${selected.y}`);status(say('Coordenadas copiadas.','Coordinates copied.'))}catch{status(label(selected))}};
$('download').onclick=async()=>{if(!slots.length)return;try{await refresh()}catch{status(say('No se pudo comprobar la versión actual. Inténtalo de nuevo.','Could not check the latest version. Please retry.'));return}canvas.toBlob(blob=>{if(!blob)return status('No se pudo generar la descarga.');const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download='HOLa-mapa-coordenadas-HD.png';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)},'image/png')};
async function init(){try{if(admin){const {data:{session}}=await sb.auth.getSession();if(!session){location.href='admin-login.html';return}const {data,error}=await sb.rpc('is_hola_r4_r5_admin');if(error||!data){status('Acceso reservado a R4/R5.');return}$('content').hidden=false;$('assign').onclick=()=>save();$('remove').onclick=()=>save(true);$('slot').onchange=()=>show(slots.find(s=>s.id===Number($('slot').value)));const {data:members}=await sb.from('players').select('name').order('name');if(members)$('members').replaceChildren(...members.map(p=>{const o=document.createElement('option');o.value=p.name;return o}))}await Promise.all(['center','mountain','building'].map(name=>new Promise(resolve=>{const im=new Image;im.onload=()=>{images[name]=im;resolve()};im.onerror=resolve;im.src=`assets/map/${name}.${name==='building'?'png':'jpg'}`})));await refresh();translate();fit();if(admin)show(slots[0],false);status('')}catch(e){status(say('No se pudo cargar el mapa. Recarga para intentarlo de nuevo.','Map could not load. Reload to try again.'));console.error(e)}}
init();
