export const LANGS={
  es:{code:'es',name:'Español',locale:'es-ES'},
  en:{code:'gb',name:'English',locale:'en-GB'},
  tr:{code:'tr',name:'Türkçe',locale:'tr-TR'},
  fr:{code:'fr',name:'Français',locale:'fr-FR'},
  de:{code:'de',name:'Deutsch',locale:'de-DE'},
  ro:{code:'ro',name:'Română',locale:'ro-RO'},
  pt:{code:'pt',name:'Português',locale:'pt-PT'},
  uk:{code:'ua',name:'Українська',locale:'uk-UA'},
  it:{code:'it',name:'Italiano',locale:'it-IT'},
  pl:{code:'pl',name:'Polski',locale:'pl-PL'},
  ru:{code:'ru',name:'Русский',locale:'ru-RU'}
};

const common={
  es:{
    pageTitle:'HOLa — Estadísticas del tren',eyebrow:'HOLa · CENTRO DE INTELIGENCIA DE LA ALIANZA',heroTitle:'ESTADÍSTICAS',heroSub:'ANÁLISIS DEL TREN',heroDesc:'Historial real del tren, rotación de conductores, origen de cada asignación y evolución de la alianza. Todos los datos se calculan desde los registros reales de HOLa.',
    loadingPeriod:'Cargando periodo…',syncing:'Sincronizando datos…',statsAria:'Tipos de estadísticas',trainTab:'TREN',soon:'PRÓX.',donations:'DONACIONES',executive:'RESUMEN EJECUTIVO',trainStatus:'Estado del tren',period:'Periodo',last4w:'ÚLTIMAS 4 SEMANAS',currentCycle:'CICLO ACTUAL',seasonS3:'TEMPORADA S3',
    registeredTrips:'VIAJES REGISTRADOS',confirmedDrivers:'conductores reales confirmados',uniqueDrivers:'CONDUCTORES ÚNICOS',rotation:'ROTACIÓN HOLa',mostTrips:'MÁS VIAJES',trainOrigin:'Origen del tren',originDesc:'Cómo se repartieron los viajes reales por día/fuente.',trips:'VIAJES',
    plannedReal:'Planificado vs real',plannedDesc:'Coincidencia entre el conductor calculado y el confirmado.',match:'COINCIDENCIA',matches:'COINCIDENCIAS',driverChanges:'CAMBIOS DE TITULAR',noPlan:'SIN PLAN CALCULABLE',driverHall:'SALÓN DE MAQUINISTAS',driverRanking:'Ranking de conductores',loadingDrivers:'Cargando conductores…',
    whoBoarded:'QUIÉN SUBIÓ AL TREN',passengersGuests:'Pasajeros e invitados',passengerSeats:'PUESTOS DE PASAJERO',passengerRecords:'registros de pasajeros en el periodo',uniquePassengers:'PASAJEROS ÚNICOS',vipGuardian:'VIP / GUARDIÁN',mostTraveler:'MÁS VIAJERO',passengerRanking:'RANKING DE PASAJEROS',mostTravelled:'Los que más han viajado',noPassengers:'Aún no hay pasajeros registrados.',driverGuest:'INVITADO DEL CONDUCTOR',vipGuardians:'VIP y Guardianes',noGuests:'Aún no hay invitados registrados.',
    timeline:'CRONOLOGÍA',weeklyHistory:'Historial semanal',buildingHistory:'Construyendo historial…',footnote:'La estadística de viajes usa únicamente conductores reales confirmados. La comparación “planificado vs real” reconstruye la planificación con los datos guardados actualmente para cada semana.',cycles:'CICLOS',last:'ÚLTIMO',back:'Volver',trainAria:'Tren',changeLanguage:'Cambiar idioma',close:'Cerrar',
    membersRegistered:'de {n} miembros registrados',withoutTrip:'{n} todavía sin viaje en este periodo',noData:'Sin datos',tie:'EMPATE ×{n}',tripOne:'viaje',tripMany:'viajes',each:'cada uno',peopleDifferent:'{n} personas diferentes',passengerTripOne:'viaje como pasajero',passengerTripMany:'viajes como pasajero',journeyOne:'VIAJE',journeyMany:'VIAJES',invitationOne:'INVITACIÓN',invitationMany:'INVITACIONES',
    noDriversPeriod:'Todavía no hay conductores registrados en este periodo.',noPassengersPeriod:'Todavía no hay pasajeros registrados en este periodo.',noGuestsPeriod:'Todavía no hay VIP o Guardianes registrados en este periodo.',cycleLabel:'CICLO {n}/4',noHistory:'Sin historial para este periodo.',plannedAndReal:'Titular calculado y conductor real',realPlanned:'Conductor real · previsto: {name}',realDriver:'Conductor real',modalPeriod:'{n} viaje{s} dentro del periodo seleccionado · {m} histórico{h}',dataReal:'DATOS REALES · {trains} TRENES · {travelers} VIAJEROS',secondaryPending:' · {n} FUENTE SECUNDARIA PENDIENTE',errorMain:'ERROR AL CARGAR DATOS PRINCIPALES',loadDriversError:'No se pudieron cargar los conductores.',loadPassengersError:'No se pudieron cargar los pasajeros.',loadGuestsError:'No se pudieron cargar los invitados.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Donaciones'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Donaciones'},days:['DOM','LUN','MAR','MIÉ','JUE','VIE','SÁB'],vip:'VIP',guardian:'GUARDIÁN'
  },
  en:{
    pageTitle:'HOLa — Train Statistics',eyebrow:'HOLa · ALLIANCE INTELLIGENCE CENTER',heroTitle:'STATISTICS',heroSub:'TRAIN ANALYTICS',heroDesc:'Real train history, driver rotation, assignment sources and alliance evolution. Every figure is calculated from HOLa’s real records.',
    loadingPeriod:'Loading period…',syncing:'Syncing data…',statsAria:'Statistics types',trainTab:'TRAIN',soon:'SOON',donations:'DONATIONS',executive:'EXECUTIVE SUMMARY',trainStatus:'Train status',period:'Period',last4w:'LAST 4 WEEKS',currentCycle:'CURRENT CYCLE',seasonS3:'SEASON S3',
    registeredTrips:'RECORDED TRIPS',confirmedDrivers:'confirmed real drivers',uniqueDrivers:'UNIQUE DRIVERS',rotation:'HOLa ROTATION',mostTrips:'MOST TRIPS',trainOrigin:'Train source',originDesc:'How real trips were distributed by day/source.',trips:'TRIPS',
    plannedReal:'Planned vs real',plannedDesc:'Match between the calculated driver and the confirmed one.',match:'MATCH',matches:'MATCHES',driverChanges:'DRIVER CHANGES',noPlan:'NO CALCULABLE PLAN',driverHall:'DRIVERS HALL',driverRanking:'Driver ranking',loadingDrivers:'Loading drivers…',
    whoBoarded:'WHO BOARDED THE TRAIN',passengersGuests:'Passengers and guests',passengerSeats:'PASSENGER SEATS',passengerRecords:'passenger records in this period',uniquePassengers:'UNIQUE PASSENGERS',vipGuardian:'VIP / GUARDIAN',mostTraveler:'MOST TRAVELLED',passengerRanking:'PASSENGER RANKING',mostTravelled:'Most frequent travellers',noPassengers:'No passengers recorded yet.',driverGuest:'DRIVER GUEST',vipGuardians:'VIPs and Guardians',noGuests:'No guests recorded yet.',
    timeline:'TIMELINE',weeklyHistory:'Weekly history',buildingHistory:'Building history…',footnote:'Trip statistics use only confirmed real drivers. “Planned vs real” rebuilds the plan using the data currently stored for each week.',cycles:'CYCLES',last:'LATEST',back:'Back',trainAria:'Train',changeLanguage:'Change language',close:'Close',
    membersRegistered:'of {n} registered members',withoutTrip:'{n} still without a trip in this period',noData:'No data',tie:'TIE ×{n}',tripOne:'trip',tripMany:'trips',each:'each',peopleDifferent:'{n} different people',passengerTripOne:'trip as passenger',passengerTripMany:'trips as passenger',journeyOne:'TRIP',journeyMany:'TRIPS',invitationOne:'INVITATION',invitationMany:'INVITATIONS',
    noDriversPeriod:'No drivers recorded in this period yet.',noPassengersPeriod:'No passengers recorded in this period yet.',noGuestsPeriod:'No VIPs or Guardians recorded in this period yet.',cycleLabel:'CYCLE {n}/4',noHistory:'No history for this period.',plannedAndReal:'Calculated driver and real driver',realPlanned:'Real driver · planned: {name}',realDriver:'Real driver',modalPeriod:'{n} trip{s} in selected period · {m} historical',dataReal:'REAL DATA · {trains} TRAINS · {travelers} TRAVELLERS',secondaryPending:' · {n} SECONDARY SOURCE PENDING',errorMain:'ERROR LOADING MAIN DATA',loadDriversError:'Drivers could not be loaded.',loadPassengersError:'Passengers could not be loaded.',loadGuestsError:'Guests could not be loaded.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Donations'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Donations'},days:['SUN','MON','TUE','WED','THU','FRI','SAT'],vip:'VIP',guardian:'GUARDIAN'
  },
  tr:{
    pageTitle:'HOLa — Tren İstatistikleri',eyebrow:'HOLa · İTTİFAK İSTİHBARAT MERKEZİ',heroTitle:'İSTATİSTİKLER',heroSub:'TREN ANALİZİ',heroDesc:'Gerçek tren geçmişi, sürücü rotasyonu, atama kaynakları ve ittifakın gelişimi. Tüm veriler HOLa’nın gerçek kayıtlarından hesaplanır.',
    loadingPeriod:'Dönem yükleniyor…',syncing:'Veriler eşitleniyor…',statsAria:'İstatistik türleri',trainTab:'TREN',soon:'YAKINDA',donations:'BAĞIŞLAR',executive:'YÖNETİCİ ÖZETİ',trainStatus:'Tren durumu',period:'Dönem',last4w:'SON 4 HAFTA',currentCycle:'MEVCUT DÖNGÜ',seasonS3:'S3 SEZONU',
    registeredTrips:'KAYITLI YOLCULUKLAR',confirmedDrivers:'onaylanmış gerçek sürücüler',uniqueDrivers:'BENZERSİZ SÜRÜCÜLER',rotation:'HOLa ROTASYONU',mostTrips:'EN ÇOK YOLCULUK',trainOrigin:'Tren kaynağı',originDesc:'Gerçek yolculukların gün/kaynağa göre dağılımı.',trips:'YOLCULUK',
    plannedReal:'Planlanan ve gerçek',plannedDesc:'Hesaplanan sürücü ile onaylanan sürücünün eşleşmesi.',match:'EŞLEŞME',matches:'EŞLEŞMELER',driverChanges:'SÜRÜCÜ DEĞİŞİKLİKLERİ',noPlan:'HESAPLANABİLİR PLAN YOK',driverHall:'SÜRÜCÜLER SALONU',driverRanking:'Sürücü sıralaması',loadingDrivers:'Sürücüler yükleniyor…',
    whoBoarded:'TRENE KİM BİNDİ',passengersGuests:'Yolcular ve misafirler',passengerSeats:'YOLCU KOLTUKLARI',passengerRecords:'bu dönemdeki yolcu kayıtları',uniquePassengers:'BENZERSİZ YOLCULAR',vipGuardian:'VIP / MUHAFIZ',mostTraveler:'EN ÇOK YOLCULUK EDEN',passengerRanking:'YOLCU SIRALAMASI',mostTravelled:'En çok yolculuk edenler',noPassengers:'Henüz yolcu kaydı yok.',driverGuest:'SÜRÜCÜNÜN MİSAFİRİ',vipGuardians:'VIP ve Muhafızlar',noGuests:'Henüz misafir kaydı yok.',
    timeline:'ZAMAN ÇİZELGESİ',weeklyHistory:'Haftalık geçmiş',buildingHistory:'Geçmiş oluşturuluyor…',footnote:'Yolculuk istatistikleri yalnızca onaylanmış gerçek sürücüleri kullanır. “Planlanan ve gerçek” karşılaştırması her hafta için mevcut kayıtlarla planı yeniden oluşturur.',cycles:'DÖNGÜLER',last:'SON',back:'Geri',trainAria:'Tren',changeLanguage:'Dili değiştir',close:'Kapat',
    membersRegistered:'{n} kayıtlı üyeden',withoutTrip:'Bu dönemde {n} kişinin henüz yolculuğu yok',noData:'Veri yok',tie:'BERABERE ×{n}',tripOne:'yolculuk',tripMany:'yolculuk',each:'kişi başı',peopleDifferent:'{n} farklı kişi',passengerTripOne:'yolcu olarak yolculuk',passengerTripMany:'yolcu olarak yolculuk',journeyOne:'YOLCULUK',journeyMany:'YOLCULUK',invitationOne:'DAVET',invitationMany:'DAVET',
    noDriversPeriod:'Bu dönemde henüz sürücü kaydı yok.',noPassengersPeriod:'Bu dönemde henüz yolcu kaydı yok.',noGuestsPeriod:'Bu dönemde henüz VIP veya Muhafız kaydı yok.',cycleLabel:'DÖNGÜ {n}/4',noHistory:'Bu dönem için geçmiş yok.',plannedAndReal:'Hesaplanan sürücü ve gerçek sürücü',realPlanned:'Gerçek sürücü · planlanan: {name}',realDriver:'Gerçek sürücü',modalPeriod:'Seçili dönemde {n} yolculuk · toplam {m}',dataReal:'GERÇEK VERİ · {trains} TREN · {travelers} YOLCU',secondaryPending:' · {n} İKİNCİL KAYNAK BEKLİYOR',errorMain:'ANA VERİLER YÜKLENEMEDİ',loadDriversError:'Sürücüler yüklenemedi.',loadPassengersError:'Yolcular yüklenemedi.',loadGuestsError:'Misafirler yüklenemedi.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Bağışlar'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Bağışlar'},days:['PAZ','PZT','SAL','ÇAR','PER','CUM','CMT'],vip:'VIP',guardian:'MUHAFIZ'
  },
  fr:{
    pageTitle:'HOLa — Statistiques du train',eyebrow:'HOLa · CENTRE DE RENSEIGNEMENT DE L’ALLIANCE',heroTitle:'STATISTIQUES',heroSub:'ANALYSE DU TRAIN',heroDesc:'Historique réel du train, rotation des conducteurs, origine des attributions et évolution de l’alliance. Toutes les données proviennent des registres réels de HOLa.',
    loadingPeriod:'Chargement de la période…',syncing:'Synchronisation des données…',statsAria:'Types de statistiques',trainTab:'TRAIN',soon:'BIENTÔT',donations:'DONS',executive:'RÉSUMÉ EXÉCUTIF',trainStatus:'État du train',period:'Période',last4w:'4 DERNIÈRES SEMAINES',currentCycle:'CYCLE ACTUEL',seasonS3:'SAISON S3',
    registeredTrips:'TRAJETS ENREGISTRÉS',confirmedDrivers:'conducteurs réels confirmés',uniqueDrivers:'CONDUCTEURS UNIQUES',rotation:'ROTATION HOLa',mostTrips:'PLUS DE TRAJETS',trainOrigin:'Origine du train',originDesc:'Répartition des trajets réels par jour/source.',trips:'TRAJETS',
    plannedReal:'Prévu vs réel',plannedDesc:'Correspondance entre le conducteur calculé et celui confirmé.',match:'CORRESPONDANCE',matches:'CORRESPONDANCES',driverChanges:'CHANGEMENTS DE CONDUCTEUR',noPlan:'AUCUN PLAN CALCULABLE',driverHall:'SALON DES CONDUCTEURS',driverRanking:'Classement des conducteurs',loadingDrivers:'Chargement des conducteurs…',
    whoBoarded:'QUI EST MONTÉ DANS LE TRAIN',passengersGuests:'Passagers et invités',passengerSeats:'PLACES PASSAGER',passengerRecords:'enregistrements passagers sur la période',uniquePassengers:'PASSAGERS UNIQUES',vipGuardian:'VIP / GARDIEN',mostTraveler:'PLUS GRAND VOYAGEUR',passengerRanking:'CLASSEMENT PASSAGERS',mostTravelled:'Ceux qui ont le plus voyagé',noPassengers:'Aucun passager enregistré pour le moment.',driverGuest:'INVITÉ DU CONDUCTEUR',vipGuardians:'VIP et Gardiens',noGuests:'Aucun invité enregistré pour le moment.',
    timeline:'CHRONOLOGIE',weeklyHistory:'Historique hebdomadaire',buildingHistory:'Création de l’historique…',footnote:'Les statistiques de trajets utilisent uniquement les conducteurs réels confirmés. « Prévu vs réel » reconstruit le plan avec les données actuellement enregistrées pour chaque semaine.',cycles:'CYCLES',last:'DERNIER',back:'Retour',trainAria:'Train',changeLanguage:'Changer de langue',close:'Fermer',
    membersRegistered:'sur {n} membres enregistrés',withoutTrip:'{n} encore sans trajet sur cette période',noData:'Aucune donnée',tie:'ÉGALITÉ ×{n}',tripOne:'trajet',tripMany:'trajets',each:'chacun',peopleDifferent:'{n} personnes différentes',passengerTripOne:'trajet comme passager',passengerTripMany:'trajets comme passager',journeyOne:'TRAJET',journeyMany:'TRAJETS',invitationOne:'INVITATION',invitationMany:'INVITATIONS',
    noDriversPeriod:'Aucun conducteur enregistré sur cette période.',noPassengersPeriod:'Aucun passager enregistré sur cette période.',noGuestsPeriod:'Aucun VIP ou Gardien enregistré sur cette période.',cycleLabel:'CYCLE {n}/4',noHistory:'Aucun historique pour cette période.',plannedAndReal:'Conducteur calculé et conducteur réel',realPlanned:'Conducteur réel · prévu : {name}',realDriver:'Conducteur réel',modalPeriod:'{n} trajet{s} sur la période sélectionnée · {m} historique',dataReal:'DONNÉES RÉELLES · {trains} TRAINS · {travelers} VOYAGEURS',secondaryPending:' · {n} SOURCE SECONDAIRE EN ATTENTE',errorMain:'ERREUR DE CHARGEMENT DES DONNÉES',loadDriversError:'Impossible de charger les conducteurs.',loadPassengersError:'Impossible de charger les passagers.',loadGuestsError:'Impossible de charger les invités.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Dons'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Dons'},days:['DIM','LUN','MAR','MER','JEU','VEN','SAM'],vip:'VIP',guardian:'GARDIEN'
  },
  de:{
    pageTitle:'HOLa — Zugstatistiken',eyebrow:'HOLa · ALLIANZ-INFORMATIONSZENTRUM',heroTitle:'STATISTIKEN',heroSub:'ZUGANALYSE',heroDesc:'Reale Zughistorie, Fahrerrotation, Herkunft der Zuteilungen und Entwicklung der Allianz. Alle Daten werden aus den echten HOLa-Aufzeichnungen berechnet.',
    loadingPeriod:'Zeitraum wird geladen…',syncing:'Daten werden synchronisiert…',statsAria:'Statistiktypen',trainTab:'ZUG',soon:'BALD',donations:'SPENDEN',executive:'ÜBERSICHT',trainStatus:'Zugstatus',period:'Zeitraum',last4w:'LETZTE 4 WOCHEN',currentCycle:'AKTUELLER ZYKLUS',seasonS3:'SAISON S3',
    registeredTrips:'ERFASSTE FAHRTEN',confirmedDrivers:'bestätigte reale Fahrer',uniqueDrivers:'EINZIGARTIGE FAHRER',rotation:'HOLa-ROTATION',mostTrips:'MEISTE FAHRTEN',trainOrigin:'Zugquelle',originDesc:'Verteilung der realen Fahrten nach Tag/Quelle.',trips:'FAHRTEN',
    plannedReal:'Geplant vs real',plannedDesc:'Übereinstimmung zwischen berechnetem und bestätigtem Fahrer.',match:'ÜBEREINSTIMMUNG',matches:'ÜBEREINSTIMMUNGEN',driverChanges:'FAHRERWECHSEL',noPlan:'KEIN BERECHENBARER PLAN',driverHall:'FAHRERHALLE',driverRanking:'Fahrerrangliste',loadingDrivers:'Fahrer werden geladen…',
    whoBoarded:'WER IM ZUG WAR',passengersGuests:'Passagiere und Gäste',passengerSeats:'PASSAGIERPLÄTZE',passengerRecords:'Passagieraufzeichnungen im Zeitraum',uniquePassengers:'EINZIGARTIGE PASSAGIERE',vipGuardian:'VIP / WÄCHTER',mostTraveler:'HÄUFIGSTER REISENDER',passengerRanking:'PASSAGIER-RANGLISTE',mostTravelled:'Am häufigsten gereist',noPassengers:'Noch keine Passagiere erfasst.',driverGuest:'GAST DES FAHRERS',vipGuardians:'VIPs und Wächter',noGuests:'Noch keine Gäste erfasst.',
    timeline:'ZEITLEISTE',weeklyHistory:'Wochenverlauf',buildingHistory:'Verlauf wird erstellt…',footnote:'Die Fahrtstatistik verwendet nur bestätigte reale Fahrer. „Geplant vs real“ rekonstruiert den Plan mit den aktuell für jede Woche gespeicherten Daten.',cycles:'ZYKLEN',last:'LETZTE',back:'Zurück',trainAria:'Zug',changeLanguage:'Sprache ändern',close:'Schließen',
    membersRegistered:'von {n} registrierten Mitgliedern',withoutTrip:'{n} in diesem Zeitraum noch ohne Fahrt',noData:'Keine Daten',tie:'GLEICHSTAND ×{n}',tripOne:'Fahrt',tripMany:'Fahrten',each:'jeweils',peopleDifferent:'{n} verschiedene Personen',passengerTripOne:'Fahrt als Passagier',passengerTripMany:'Fahrten als Passagier',journeyOne:'FAHRT',journeyMany:'FAHRTEN',invitationOne:'EINLADUNG',invitationMany:'EINLADUNGEN',
    noDriversPeriod:'In diesem Zeitraum sind noch keine Fahrer erfasst.',noPassengersPeriod:'In diesem Zeitraum sind noch keine Passagiere erfasst.',noGuestsPeriod:'In diesem Zeitraum sind noch keine VIPs oder Wächter erfasst.',cycleLabel:'ZYKLUS {n}/4',noHistory:'Kein Verlauf für diesen Zeitraum.',plannedAndReal:'Berechneter Fahrer und realer Fahrer',realPlanned:'Realer Fahrer · geplant: {name}',realDriver:'Realer Fahrer',modalPeriod:'{n} Fahrt(en) im gewählten Zeitraum · {m} historisch',dataReal:'ECHTE DATEN · {trains} ZÜGE · {travelers} REISENDE',secondaryPending:' · {n} SEKUNDÄRQUELLE AUSSTEHEND',errorMain:'FEHLER BEIM LADEN DER HAUPTDATEN',loadDriversError:'Fahrer konnten nicht geladen werden.',loadPassengersError:'Passagiere konnten nicht geladen werden.',loadGuestsError:'Gäste konnten nicht geladen werden.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Spenden'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Spenden'},days:['SO','MO','DI','MI','DO','FR','SA'],vip:'VIP',guardian:'WÄCHTER'
  },
  ro:{
    pageTitle:'HOLa — Statistici tren',eyebrow:'HOLa · CENTRUL DE INFORMAȚII AL ALIANȚEI',heroTitle:'STATISTICI',heroSub:'ANALIZA TRENULUI',heroDesc:'Istoricul real al trenului, rotația conductorilor, sursa atribuirilor și evoluția alianței. Toate datele sunt calculate din înregistrările reale HOLa.',
    loadingPeriod:'Se încarcă perioada…',syncing:'Se sincronizează datele…',statsAria:'Tipuri de statistici',trainTab:'TREN',soon:'ÎN CURÂND',donations:'DONAȚII',executive:'REZUMAT',trainStatus:'Starea trenului',period:'Perioadă',last4w:'ULTIMELE 4 SĂPTĂMÂNI',currentCycle:'CICLUL ACTUAL',seasonS3:'SEZONUL S3',
    registeredTrips:'CĂLĂTORII ÎNREGISTRATE',confirmedDrivers:'conductori reali confirmați',uniqueDrivers:'CONDUCTORI UNICI',rotation:'ROTAȚIE HOLa',mostTrips:'CELE MAI MULTE CĂLĂTORII',trainOrigin:'Sursa trenului',originDesc:'Cum s-au distribuit călătoriile reale după zi/sursă.',trips:'CĂLĂTORII',
    plannedReal:'Planificat vs real',plannedDesc:'Potrivirea dintre conductorul calculat și cel confirmat.',match:'POTRIVIRE',matches:'POTRIVIRI',driverChanges:'SCHIMBĂRI DE CONDUCTOR',noPlan:'FĂRĂ PLAN CALCULABIL',driverHall:'SALA CONDUCTORILOR',driverRanking:'Clasament conductori',loadingDrivers:'Se încarcă conductorii…',
    whoBoarded:'CINE A URCAT ÎN TREN',passengersGuests:'Pasageri și invitați',passengerSeats:'LOCURI PASAGERI',passengerRecords:'înregistrări de pasageri în perioadă',uniquePassengers:'PASAGERI UNICI',vipGuardian:'VIP / PAZNIC',mostTraveler:'CEL MAI FRECVENT CĂLĂTOR',passengerRanking:'CLASAMENT PASAGERI',mostTravelled:'Cei care au călătorit cel mai mult',noPassengers:'Nu sunt încă pasageri înregistrați.',driverGuest:'INVITATUL CONDUCTORULUI',vipGuardians:'VIP și Paznici',noGuests:'Nu sunt încă invitați înregistrați.',
    timeline:'CRONOLOGIE',weeklyHistory:'Istoric săptămânal',buildingHistory:'Se construiește istoricul…',footnote:'Statisticile de călătorie folosesc doar conductorii reali confirmați. „Planificat vs real” reconstruiește planificarea cu datele stocate în prezent pentru fiecare săptămână.',cycles:'CICLURI',last:'ULTIMUL',back:'Înapoi',trainAria:'Tren',changeLanguage:'Schimbă limba',close:'Închide',
    membersRegistered:'din {n} membri înregistrați',withoutTrip:'{n} încă fără călătorie în această perioadă',noData:'Fără date',tie:'EGALITATE ×{n}',tripOne:'călătorie',tripMany:'călătorii',each:'fiecare',peopleDifferent:'{n} persoane diferite',passengerTripOne:'călătorie ca pasager',passengerTripMany:'călătorii ca pasager',journeyOne:'CĂLĂTORIE',journeyMany:'CĂLĂTORII',invitationOne:'INVITAȚIE',invitationMany:'INVITAȚII',
    noDriversPeriod:'Nu sunt încă conductori înregistrați în această perioadă.',noPassengersPeriod:'Nu sunt încă pasageri înregistrați în această perioadă.',noGuestsPeriod:'Nu sunt încă VIP sau Paznici înregistrați în această perioadă.',cycleLabel:'CICLU {n}/4',noHistory:'Nu există istoric pentru această perioadă.',plannedAndReal:'Conductor calculat și conductor real',realPlanned:'Conductor real · planificat: {name}',realDriver:'Conductor real',modalPeriod:'{n} călătorii în perioada selectată · {m} istorice',dataReal:'DATE REALE · {trains} TRENURI · {travelers} CĂLĂTORI',secondaryPending:' · {n} SURSĂ SECUNDARĂ ÎN AȘTEPTARE',errorMain:'EROARE LA ÎNCĂRCAREA DATELOR PRINCIPALE',loadDriversError:'Conductorii nu au putut fi încărcați.',loadPassengersError:'Pasagerii nu au putut fi încărcați.',loadGuestsError:'Invitații nu au putut fi încărcați.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Donații'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Donații'},days:['DUM','LUN','MAR','MIE','JOI','VIN','SÂM'],vip:'VIP',guardian:'PAZNIC'
  },
  pt:{
    pageTitle:'HOLa — Estatísticas do comboio',eyebrow:'HOLa · CENTRO DE INTELIGÊNCIA DA ALIANÇA',heroTitle:'ESTATÍSTICAS',heroSub:'ANÁLISE DO COMBOIO',heroDesc:'Histórico real do comboio, rotação de condutores, origem das atribuições e evolução da aliança. Todos os dados são calculados a partir dos registos reais da HOLa.',
    loadingPeriod:'A carregar período…',syncing:'A sincronizar dados…',statsAria:'Tipos de estatísticas',trainTab:'COMBOIO',soon:'EM BREVE',donations:'DOAÇÕES',executive:'RESUMO EXECUTIVO',trainStatus:'Estado do comboio',period:'Período',last4w:'ÚLTIMAS 4 SEMANAS',currentCycle:'CICLO ATUAL',seasonS3:'TEMPORADA S3',
    registeredTrips:'VIAGENS REGISTADAS',confirmedDrivers:'condutores reais confirmados',uniqueDrivers:'CONDUTORES ÚNICOS',rotation:'ROTAÇÃO HOLa',mostTrips:'MAIS VIAGENS',trainOrigin:'Origem do comboio',originDesc:'Distribuição das viagens reais por dia/origem.',trips:'VIAGENS',
    plannedReal:'Planeado vs real',plannedDesc:'Correspondência entre o condutor calculado e o confirmado.',match:'CORRESPONDÊNCIA',matches:'CORRESPONDÊNCIAS',driverChanges:'MUDANÇAS DE CONDUTOR',noPlan:'SEM PLANO CALCULÁVEL',driverHall:'SALÃO DOS CONDUTORES',driverRanking:'Ranking de condutores',loadingDrivers:'A carregar condutores…',
    whoBoarded:'QUEM ENTROU NO COMBOIO',passengersGuests:'Passageiros e convidados',passengerSeats:'LUGARES DE PASSAGEIRO',passengerRecords:'registos de passageiros no período',uniquePassengers:'PASSAGEIROS ÚNICOS',vipGuardian:'VIP / GUARDIÃO',mostTraveler:'MAIS VIAJANTE',passengerRanking:'RANKING DE PASSAGEIROS',mostTravelled:'Quem mais viajou',noPassengers:'Ainda não há passageiros registados.',driverGuest:'CONVIDADO DO CONDUTOR',vipGuardians:'VIP e Guardiões',noGuests:'Ainda não há convidados registados.',
    timeline:'CRONOLOGIA',weeklyHistory:'Histórico semanal',buildingHistory:'A construir histórico…',footnote:'As estatísticas de viagens usam apenas condutores reais confirmados. “Planeado vs real” reconstrói o planeamento com os dados atualmente guardados para cada semana.',cycles:'CICLOS',last:'ÚLTIMO',back:'Voltar',trainAria:'Comboio',changeLanguage:'Mudar idioma',close:'Fechar',
    membersRegistered:'de {n} membros registados',withoutTrip:'{n} ainda sem viagem neste período',noData:'Sem dados',tie:'EMPATE ×{n}',tripOne:'viagem',tripMany:'viagens',each:'cada um',peopleDifferent:'{n} pessoas diferentes',passengerTripOne:'viagem como passageiro',passengerTripMany:'viagens como passageiro',journeyOne:'VIAGEM',journeyMany:'VIAGENS',invitationOne:'CONVITE',invitationMany:'CONVITES',
    noDriversPeriod:'Ainda não há condutores registados neste período.',noPassengersPeriod:'Ainda não há passageiros registados neste período.',noGuestsPeriod:'Ainda não há VIP ou Guardiões registados neste período.',cycleLabel:'CICLO {n}/4',noHistory:'Sem histórico para este período.',plannedAndReal:'Condutor calculado e condutor real',realPlanned:'Condutor real · previsto: {name}',realDriver:'Condutor real',modalPeriod:'{n} viagem(ns) no período selecionado · {m} históricas',dataReal:'DADOS REAIS · {trains} COMBOIOS · {travelers} VIAJANTES',secondaryPending:' · {n} FONTE SECUNDÁRIA PENDENTE',errorMain:'ERRO AO CARREGAR DADOS PRINCIPAIS',loadDriversError:'Não foi possível carregar os condutores.',loadPassengersError:'Não foi possível carregar os passageiros.',loadGuestsError:'Não foi possível carregar os convidados.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Doações'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Doações'},days:['DOM','SEG','TER','QUA','QUI','SEX','SÁB'],vip:'VIP',guardian:'GUARDIÃO'
  },
  uk:{
    pageTitle:'HOLa — Статистика потяга',eyebrow:'HOLa · РОЗВІДУВАЛЬНИЙ ЦЕНТР АЛЬЯНСУ',heroTitle:'СТАТИСТИКА',heroSub:'АНАЛІТИКА ПОТЯГА',heroDesc:'Реальна історія потяга, ротація машиністів, джерела призначень і розвиток альянсу. Усі дані розраховані з реальних записів HOLa.',
    loadingPeriod:'Завантаження періоду…',syncing:'Синхронізація даних…',statsAria:'Типи статистики',trainTab:'ПОТЯГ',soon:'НЕЗАБАРОМ',donations:'ПОЖЕРТВИ',executive:'ПІДСУМОК',trainStatus:'Стан потяга',period:'Період',last4w:'ОСТАННІ 4 ТИЖНІ',currentCycle:'ПОТОЧНИЙ ЦИКЛ',seasonS3:'СЕЗОН S3',
    registeredTrips:'ЗАРЕЄСТРОВАНІ ПОЇЗДКИ',confirmedDrivers:'підтверджені реальні машиністи',uniqueDrivers:'УНІКАЛЬНІ МАШИНІСТИ',rotation:'РОТАЦІЯ HOLa',mostTrips:'НАЙБІЛЬШЕ ПОЇЗДОК',trainOrigin:'Джерело потяга',originDesc:'Розподіл реальних поїздок за днем/джерелом.',trips:'ПОЇЗДКИ',
    plannedReal:'Заплановано vs реально',plannedDesc:'Збіг між розрахованим і підтвердженим машиністом.',match:'ЗБІГ',matches:'ЗБІГИ',driverChanges:'ЗМІНИ МАШИНІСТА',noPlan:'НЕМАЄ РОЗРАХОВАНОГО ПЛАНУ',driverHall:'ЗАЛ МАШИНІСТІВ',driverRanking:'Рейтинг машиністів',loadingDrivers:'Завантаження машиністів…',
    whoBoarded:'ХТО СІВ У ПОТЯГ',passengersGuests:'Пасажири та гості',passengerSeats:'МІСЦЯ ПАСАЖИРІВ',passengerRecords:'записи пасажирів за період',uniquePassengers:'УНІКАЛЬНІ ПАСАЖИРИ',vipGuardian:'VIP / ОХОРОНЕЦЬ',mostTraveler:'НАЙЧАСТІШИЙ МАНДРІВНИК',passengerRanking:'РЕЙТИНГ ПАСАЖИРІВ',mostTravelled:'Ті, хто подорожував найбільше',noPassengers:'Пасажирів ще не зареєстровано.',driverGuest:'ГІСТЬ МАШИНІСТА',vipGuardians:'VIP та Охоронці',noGuests:'Гостей ще не зареєстровано.',
    timeline:'ХРОНОЛОГІЯ',weeklyHistory:'Тижнева історія',buildingHistory:'Створення історії…',footnote:'Статистика поїздок використовує лише підтверджених реальних машиністів. «Заплановано vs реально» відновлює план із даних, які зараз збережені для кожного тижня.',cycles:'ЦИКЛИ',last:'ОСТАННІЙ',back:'Назад',trainAria:'Потяг',changeLanguage:'Змінити мову',close:'Закрити',
    membersRegistered:'із {n} зареєстрованих учасників',withoutTrip:'{n} ще без поїздки в цьому періоді',noData:'Немає даних',tie:'НІЧИЯ ×{n}',tripOne:'поїздка',tripMany:'поїздок',each:'кожен',peopleDifferent:'{n} різних людей',passengerTripOne:'поїздка як пасажир',passengerTripMany:'поїздок як пасажир',journeyOne:'ПОЇЗДКА',journeyMany:'ПОЇЗДКИ',invitationOne:'ЗАПРОШЕННЯ',invitationMany:'ЗАПРОШЕННЯ',
    noDriversPeriod:'У цьому періоді ще немає зареєстрованих машиністів.',noPassengersPeriod:'У цьому періоді ще немає зареєстрованих пасажирів.',noGuestsPeriod:'У цьому періоді ще немає VIP або Охоронців.',cycleLabel:'ЦИКЛ {n}/4',noHistory:'Немає історії за цей період.',plannedAndReal:'Розрахований і реальний машиніст',realPlanned:'Реальний машиніст · заплановано: {name}',realDriver:'Реальний машиніст',modalPeriod:'{n} поїздок у вибраному періоді · {m} історично',dataReal:'РЕАЛЬНІ ДАНІ · {trains} ПОТЯГІВ · {travelers} МАНДРІВНИКІВ',secondaryPending:' · {n} ДОДАТКОВЕ ДЖЕРЕЛО ОЧІКУЄ',errorMain:'ПОМИЛКА ЗАВАНТАЖЕННЯ ОСНОВНИХ ДАНИХ',loadDriversError:'Не вдалося завантажити машиністів.',loadPassengersError:'Не вдалося завантажити пасажирів.',loadGuestsError:'Не вдалося завантажити гостей.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Пожертви'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Пожертви'},days:['НД','ПН','ВТ','СР','ЧТ','ПТ','СБ'],vip:'VIP',guardian:'ОХОРОНЕЦЬ'
  },
  it:{
    pageTitle:'HOLa — Statistiche del treno',eyebrow:'HOLa · CENTRO INFORMAZIONI DELL’ALLEANZA',heroTitle:'STATISTICHE',heroSub:'ANALISI DEL TRENO',heroDesc:'Storico reale del treno, rotazione dei conducenti, origine delle assegnazioni ed evoluzione dell’alleanza. Tutti i dati sono calcolati dai registri reali di HOLa.',
    loadingPeriod:'Caricamento periodo…',syncing:'Sincronizzazione dati…',statsAria:'Tipi di statistiche',trainTab:'TRENO',soon:'PROSS.',donations:'DONAZIONI',executive:'RIEPILOGO',trainStatus:'Stato del treno',period:'Periodo',last4w:'ULTIME 4 SETTIMANE',currentCycle:'CICLO ATTUALE',seasonS3:'STAGIONE S3',
    registeredTrips:'VIAGGI REGISTRATI',confirmedDrivers:'conducenti reali confermati',uniqueDrivers:'CONDUCENTI UNICI',rotation:'ROTAZIONE HOLa',mostTrips:'PIÙ VIAGGI',trainOrigin:'Origine del treno',originDesc:'Distribuzione dei viaggi reali per giorno/origine.',trips:'VIAGGI',
    plannedReal:'Pianificato vs reale',plannedDesc:'Corrispondenza tra il conducente calcolato e quello confermato.',match:'CORRISPONDENZA',matches:'CORRISPONDENZE',driverChanges:'CAMBI CONDUCENTE',noPlan:'NESSUN PIANO CALCOLABILE',driverHall:'SALA CONDUCENTI',driverRanking:'Classifica conducenti',loadingDrivers:'Caricamento conducenti…',
    whoBoarded:'CHI È SALITO SUL TRENO',passengersGuests:'Passeggeri e invitati',passengerSeats:'POSTI PASSEGGERO',passengerRecords:'registrazioni passeggeri nel periodo',uniquePassengers:'PASSEGGERI UNICI',vipGuardian:'VIP / GUARDIANO',mostTraveler:'PIÙ VIAGGIATORE',passengerRanking:'CLASSIFICA PASSEGGERI',mostTravelled:'Chi ha viaggiato di più',noPassengers:'Nessun passeggero ancora registrato.',driverGuest:'OSPITE DEL CONDUCENTE',vipGuardians:'VIP e Guardiani',noGuests:'Nessun ospite ancora registrato.',
    timeline:'CRONOLOGIA',weeklyHistory:'Storico settimanale',buildingHistory:'Creazione storico…',footnote:'Le statistiche dei viaggi usano solo conducenti reali confermati. “Pianificato vs reale” ricostruisce la pianificazione usando i dati attualmente salvati per ogni settimana.',cycles:'CICLI',last:'ULTIMO',back:'Indietro',trainAria:'Treno',changeLanguage:'Cambia lingua',close:'Chiudi',
    membersRegistered:'su {n} membri registrati',withoutTrip:'{n} ancora senza viaggio in questo periodo',noData:'Nessun dato',tie:'PARI ×{n}',tripOne:'viaggio',tripMany:'viaggi',each:'ciascuno',peopleDifferent:'{n} persone diverse',passengerTripOne:'viaggio come passeggero',passengerTripMany:'viaggi come passeggero',journeyOne:'VIAGGIO',journeyMany:'VIAGGI',invitationOne:'INVITO',invitationMany:'INVITI',
    noDriversPeriod:'Nessun conducente registrato in questo periodo.',noPassengersPeriod:'Nessun passeggero registrato in questo periodo.',noGuestsPeriod:'Nessun VIP o Guardiano registrato in questo periodo.',cycleLabel:'CICLO {n}/4',noHistory:'Nessuno storico per questo periodo.',plannedAndReal:'Conducente calcolato e conducente reale',realPlanned:'Conducente reale · previsto: {name}',realDriver:'Conducente reale',modalPeriod:'{n} viaggio/i nel periodo selezionato · {m} storici',dataReal:'DATI REALI · {trains} TRENI · {travelers} VIAGGIATORI',secondaryPending:' · {n} FONTE SECONDARIA IN ATTESA',errorMain:'ERRORE NEL CARICAMENTO DEI DATI PRINCIPALI',loadDriversError:'Impossibile caricare i conducenti.',loadPassengersError:'Impossibile caricare i passeggeri.',loadGuestsError:'Impossibile caricare gli ospiti.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Donazioni'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Donazioni'},days:['DOM','LUN','MAR','MER','GIO','VEN','SAB'],vip:'VIP',guardian:'GUARDIANO'
  },
  pl:{
    pageTitle:'HOLa — Statystyki pociągu',eyebrow:'HOLa · CENTRUM INFORMACYJNE SOJUSZU',heroTitle:'STATYSTYKI',heroSub:'ANALIZA POCIĄGU',heroDesc:'Rzeczywista historia pociągu, rotacja maszynistów, źródła przydziałów i rozwój sojuszu. Wszystkie dane są obliczane na podstawie rzeczywistych zapisów HOLa.',
    loadingPeriod:'Ładowanie okresu…',syncing:'Synchronizacja danych…',statsAria:'Rodzaje statystyk',trainTab:'POCIĄG',soon:'WKRÓTCE',donations:'DAROWIZNY',executive:'PODSUMOWANIE',trainStatus:'Stan pociągu',period:'Okres',last4w:'OSTATNIE 4 TYGODNIE',currentCycle:'BIEŻĄCY CYKL',seasonS3:'SEZON S3',
    registeredTrips:'ZAREJESTROWANE PRZEJAZDY',confirmedDrivers:'potwierdzeni prawdziwi maszyniści',uniqueDrivers:'UNIKALNI MASZYNIŚCI',rotation:'ROTACJA HOLa',mostTrips:'NAJWIĘCEJ PRZEJAZDÓW',trainOrigin:'Źródło pociągu',originDesc:'Rozkład rzeczywistych przejazdów według dnia/źródła.',trips:'PRZEJAZDY',
    plannedReal:'Plan vs rzeczywistość',plannedDesc:'Zgodność między wyliczonym a potwierdzonym maszynistą.',match:'ZGODNOŚĆ',matches:'ZGODNOŚCI',driverChanges:'ZMIANY MASZYNISTY',noPlan:'BRAK PLANU DO WYLICZENIA',driverHall:'SALA MASZYNISTÓW',driverRanking:'Ranking maszynistów',loadingDrivers:'Ładowanie maszynistów…',
    whoBoarded:'KTO WSIADŁ DO POCIĄGU',passengersGuests:'Pasażerowie i goście',passengerSeats:'MIEJSCA PASAŻERÓW',passengerRecords:'zapisy pasażerów w okresie',uniquePassengers:'UNIKALNI PASAŻEROWIE',vipGuardian:'VIP / STRAŻNIK',mostTraveler:'NAJCZĘSTSZY PODRÓŻNY',passengerRanking:'RANKING PASAŻERÓW',mostTravelled:'Najczęściej podróżujący',noPassengers:'Nie ma jeszcze zarejestrowanych pasażerów.',driverGuest:'GOŚĆ MASZYNISTY',vipGuardians:'VIP i Strażnicy',noGuests:'Nie ma jeszcze zarejestrowanych gości.',
    timeline:'OŚ CZASU',weeklyHistory:'Historia tygodniowa',buildingHistory:'Tworzenie historii…',footnote:'Statystyki przejazdów używają wyłącznie potwierdzonych rzeczywistych maszynistów. „Plan vs rzeczywistość” odtwarza plan na podstawie danych obecnie zapisanych dla każdego tygodnia.',cycles:'CYKLE',last:'OSTATNI',back:'Wstecz',trainAria:'Pociąg',changeLanguage:'Zmień język',close:'Zamknij',
    membersRegistered:'z {n} zarejestrowanych członków',withoutTrip:'{n} nadal bez przejazdu w tym okresie',noData:'Brak danych',tie:'REMIS ×{n}',tripOne:'przejazd',tripMany:'przejazdy',each:'każdy',peopleDifferent:'{n} różnych osób',passengerTripOne:'przejazd jako pasażer',passengerTripMany:'przejazdy jako pasażer',journeyOne:'PRZEJAZD',journeyMany:'PRZEJAZDY',invitationOne:'ZAPROSZENIE',invitationMany:'ZAPROSZENIA',
    noDriversPeriod:'Brak maszynistów w tym okresie.',noPassengersPeriod:'Brak pasażerów w tym okresie.',noGuestsPeriod:'Brak VIP-ów lub Strażników w tym okresie.',cycleLabel:'CYKL {n}/4',noHistory:'Brak historii dla tego okresu.',plannedAndReal:'Wyliczony i rzeczywisty maszynista',realPlanned:'Rzeczywisty maszynista · planowany: {name}',realDriver:'Rzeczywisty maszynista',modalPeriod:'{n} przejazdów w wybranym okresie · {m} historycznie',dataReal:'RZECZYWISTE DANE · {trains} POCIĄGÓW · {travelers} PODRÓŻNYCH',secondaryPending:' · {n} ŹRÓDŁO DODATKOWE OCZEKUJE',errorMain:'BŁĄD ŁADOWANIA GŁÓWNYCH DANYCH',loadDriversError:'Nie udało się załadować maszynistów.',loadPassengersError:'Nie udało się załadować pasażerów.',loadGuestsError:'Nie udało się załadować gości.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Darowizny'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Darowizny'},days:['ND','PN','WT','ŚR','CZW','PT','SB'],vip:'VIP',guardian:'STRAŻNIK'
  },
  ru:{
    pageTitle:'HOLa — Статистика поезда',eyebrow:'HOLa · ИНФОРМАЦИОННЫЙ ЦЕНТР АЛЬЯНСА',heroTitle:'СТАТИСТИКА',heroSub:'АНАЛИТИКА ПОЕЗДА',heroDesc:'Реальная история поезда, ротация машинистов, источники назначений и развитие альянса. Все данные рассчитываются по реальным записям HOLa.',
    loadingPeriod:'Загрузка периода…',syncing:'Синхронизация данных…',statsAria:'Типы статистики',trainTab:'ПОЕЗД',soon:'СКОРО',donations:'ПОЖЕРТВОВАНИЯ',executive:'СВОДКА',trainStatus:'Состояние поезда',period:'Период',last4w:'ПОСЛЕДНИЕ 4 НЕДЕЛИ',currentCycle:'ТЕКУЩИЙ ЦИКЛ',seasonS3:'СЕЗОН S3',
    registeredTrips:'ЗАРЕГИСТРИРОВАННЫЕ ПОЕЗДКИ',confirmedDrivers:'подтверждённые реальные машинисты',uniqueDrivers:'УНИКАЛЬНЫЕ МАШИНИСТЫ',rotation:'РОТАЦИЯ HOLa',mostTrips:'БОЛЬШЕ ВСЕГО ПОЕЗДОК',trainOrigin:'Источник поезда',originDesc:'Распределение реальных поездок по дням/источникам.',trips:'ПОЕЗДКИ',
    plannedReal:'План vs факт',plannedDesc:'Совпадение рассчитанного машиниста с подтверждённым.',match:'СОВПАДЕНИЕ',matches:'СОВПАДЕНИЯ',driverChanges:'СМЕНЫ МАШИНИСТА',noPlan:'НЕТ РАССЧИТАННОГО ПЛАНА',driverHall:'ЗАЛ МАШИНИСТОВ',driverRanking:'Рейтинг машинистов',loadingDrivers:'Загрузка машинистов…',
    whoBoarded:'КТО ЕХАЛ В ПОЕЗДЕ',passengersGuests:'Пассажиры и гости',passengerSeats:'МЕСТА ПАССАЖИРОВ',passengerRecords:'записи пассажиров за период',uniquePassengers:'УНИКАЛЬНЫЕ ПАССАЖИРЫ',vipGuardian:'VIP / ХРАНИТЕЛЬ',mostTraveler:'САМЫЙ ЧАСТЫЙ ПАССАЖИР',passengerRanking:'РЕЙТИНГ ПАССАЖИРОВ',mostTravelled:'Кто ездил чаще всего',noPassengers:'Пассажиры пока не зарегистрированы.',driverGuest:'ГОСТЬ МАШИНИСТА',vipGuardians:'VIP и Хранители',noGuests:'Гости пока не зарегистрированы.',
    timeline:'ХРОНОЛОГИЯ',weeklyHistory:'История по неделям',buildingHistory:'Формирование истории…',footnote:'Статистика поездок использует только подтверждённых реальных машинистов. «План vs факт» восстанавливает план по данным, которые сейчас сохранены для каждой недели.',cycles:'ЦИКЛЫ',last:'ПОСЛЕДНИЙ',back:'Назад',trainAria:'Поезд',changeLanguage:'Изменить язык',close:'Закрыть',
    membersRegistered:'из {n} зарегистрированных участников',withoutTrip:'{n} ещё без поездки в этом периоде',noData:'Нет данных',tie:'НИЧЬЯ ×{n}',tripOne:'поездка',tripMany:'поездок',each:'у каждого',peopleDifferent:'{n} разных человек',passengerTripOne:'поездка пассажиром',passengerTripMany:'поездок пассажиром',journeyOne:'ПОЕЗДКА',journeyMany:'ПОЕЗДКИ',invitationOne:'ПРИГЛАШЕНИЕ',invitationMany:'ПРИГЛАШЕНИЯ',
    noDriversPeriod:'В этом периоде машинисты пока не зарегистрированы.',noPassengersPeriod:'В этом периоде пассажиры пока не зарегистрированы.',noGuestsPeriod:'В этом периоде VIP или Хранители пока не зарегистрированы.',cycleLabel:'ЦИКЛ {n}/4',noHistory:'Нет истории за этот период.',plannedAndReal:'Рассчитанный и реальный машинист',realPlanned:'Реальный машинист · план: {name}',realDriver:'Реальный машинист',modalPeriod:'{n} поездок в выбранном периоде · {m} всего',dataReal:'РЕАЛЬНЫЕ ДАННЫЕ · {trains} ПОЕЗДОВ · {travelers} ПАССАЖИРОВ',secondaryPending:' · {n} ДОП. ИСТОЧНИК ОЖИДАЕТ',errorMain:'ОШИБКА ЗАГРУЗКИ ОСНОВНЫХ ДАННЫХ',loadDriversError:'Не удалось загрузить машинистов.',loadPassengersError:'Не удалось загрузить пассажиров.',loadGuestsError:'Не удалось загрузить гостей.',
    sources:{VS:'VS',DS_B:'DS B',DS_A:'DS A',DONATIONS:'Пожертвования'},sourceLong:{VS:'Versus',DS_B:'Desert Storm B',DS_A:'Desert Storm A',DONATIONS:'Пожертвования'},days:['ВС','ПН','ВТ','СР','ЧТ','ПТ','СБ'],vip:'VIP',guardian:'ХРАНИТЕЛЬ'
  }
};

// Dutch-style fallback isn't needed: every HOLa language is explicit.
export const I18N=common;
export function fill(template,vars={}){
  return String(template??'').replace(/\{(\w+)\}/g,(_,key)=>vars[key]??'');
}
